### ISSUE TITLE
http://repo.joist.ws/ is down

### ISSUE THREAD

**Issue by lalmeras** [stephenh/joist#19]
Hello,

It seems that http://repo.joist.ws/ is down. Is it possible to bring it back ?

**Comment by stephenh** [comment]
Hi!

Wow, sorry about that; honestly I didn't know that anyone used it, so I shutdown the ~$20/month VPC host I'd been basically-not-using for ~5 years. 

I do have some time today; maybe I'll finally figure out how to get joist in Maven central...

**Comment by lalmeras** [comment]
Hello,

No need to spend some time and energy just for me on this; I just wanted the issue to be aknownledged.

I only use joist-util (as a dependency of bindgen, a project that uses joist-util to generate code). I already workaround the service outage by publishing a copy of artifacts on my project repository, so I can handle it on my own.

Interested to be notified if you choose to push it on Maven central.

**Comment by stephenh** [comment]
Ah sure, that makes sense. I've requested the `ws.joist` namespace in maven and will see how it goes.

**Comment by stephenh** [comment]
Well, so good news/bad news; good news is that jitpack.io is pretty spiffy, so I have artifacts for joist itself hosted there now:

https://jitpack.io/#stephenh/joist

Granted, the artifact name changed to have "com.github.stephenh" in it.

The wrinkle/bad news is that, since you're using bindgen, I should ideally publish a new version of bindgen, which I'd probably do to jitpack.io given how easy it is, but bindgen is still using a release old ant/ivy setup that I used to use.

It sounds like jitpack actually does support ant:

https://github.com/jitpack/jitpack.io/issues/127

But it needs a top-level build.xml, and bindgen is setup as a multi-project repo (which would be just fine if it used gradle).

...so, I think I'm going to close this issue as fixed, but if you'd like to follow up with a PR against bindgen that makes it work in jitpack (the easiest is probably to just port it to gradle), that'd be great!

**Comment by lalmeras** [comment]
Thank you for your feedback.

I already fork bindgen to perform some work on it, so I do not have any need you publish it.

If anyone interested by this, it is here : https://github.com/igloo-project/bindgen/ and we publish it on our nexus repository : https://nexus.tools.kobalt.fr/#browse/browse:igloo-releases:org%2Fbindgen%2Fbindgen%2F4.0.2 (not sure why our repository is not marked as a fork of joist despite it is).

I remember we work we mainly work on build system (maven), some exclude mechanism, possibility not to regenerate bindings provided in dependencies, and use of lambda instead of embedded classes when it is possible.
